### 1. How does data look like?
POST https://<mTLS_ENDPOINT_DNS_GOES_HERE>/search/
Content-Type: application/json

{
  "yql": "select * from article where true"
}

### 2. Hybrid search on article as a whole
### NOTE: we match on per-chunk embeddings but we don't rank on them (yet)
POST https://<mTLS_ENDPOINT_DNS_GOES_HERE>/search/
Content-Type: application/json

{
  "yql": "select * from article where ({targetHits:100}nearestNeighbor(article_title_embedding,q_embedding)) OR ({targetHits:100}nearestNeighbor(chunk_embeddings,q_embedding)) OR userQuery()",
  "query": "binary entropy",
  "input.query(q_embedding)": "embed(@query)",
  "ranking.profile": "per_doc"
}

### 3. Lexical search per chunk
POST https://<mTLS_ENDPOINT_DNS_GOES_HERE>/search/
Content-Type: application/json

{
  "yql": "select * from article where userQuery()",
  "query": "binary entropy",
  "ranking.profile": "per_chunk_lexical",
  "summary": "top_3_chunks_bm25"
}

### 4. Semantic search per chunk
POST https://<mTLS_ENDPOINT_DNS_GOES_HERE>/search/
Content-Type: application/json

{
  "yql": "select * from article where {targetHits:100}nearestNeighbor(chunk_embeddings,q_embedding)",
  "query": "binary entropy",
  "input.query(q_embedding)": "embed(@query)",
  "ranking.profile": "per_chunk_semantic",
  "summary": "top_3_chunks_semantic"
}

### 5. Article+chunk hybrid search
POST https://<mTLS_ENDPOINT_DNS_GOES_HERE>/search/
Content-Type: application/json

{
  "yql": "select * from article where ({targetHits:100}nearestNeighbor(article_title_embedding,q_embedding)) OR ({targetHits:100}nearestNeighbor(chunk_embeddings,q_embedding)) OR userQuery()",
  "query": "binary entropy",
  "input.query(q_embedding)": "embed(@query)",
  "ranking.profile": "doc_and_chunks_hybrid",
  "summary": "top_3_chunks_by_hybrid_score"
}

