

### hybrid query
POST https://<mTLS_ENDPOINT_DNS_GOES_HERE>/search/
Content-Type: application/json

{
  "yql": "select * from product where ({targetHits:100}nearestNeighbor(ProductName_embedding,q_embedding)) OR ({targetHits:100}nearestNeighbor(Description_embedding,q_embedding)) OR userQuery()",
  "query": "home decor items",
  "input.query(q_embedding)": "embed(@query)",
  "ranking.profile": "hybrid",
  "hits": 20
}